import Head from 'next/head';
import { getSession, signOut, useSession } from 'next-auth/react';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  const { data: session } = useSession();

  const handleSignOut = () => {
    signOut();
  };
  return (
    <>
      <Head>
        <title>User Details</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      {session && User({ session, handleSignOut })}
    </>
  );
}

function User({ session, handleSignOut }) {
  return (
    <div className='flex h-screen items-center bg-darkPurple'>
      <div className='grid grid-cols-1 p-4 mx-auto rounded-md max-w-5xl'>
        <div className='rounded-t-md bg-lightPurple p-4'>
          <div className='flex flex-row justify-between text-mainPurple font-medium text-2xl'>
            <span>{session?.user?.name}</span>
            {session?.user?.image && (
              <Image
                src={session.user.image}
                width={40}
                height={40}
                alt='icon'
                className='rounded-full'
              />
            )}
          </div>
        </div>
        <div className='flex flex-col rounded-b-md bg-white p-6 gap-4 pb-10'>
          <h2 className='text-semibold text-3xl pt-2 text-center'>Dashboard</h2>
          <p>You are seeing this page because your login is successful.</p>
          <div className='flex flex-col pb-4'>
            <span className='text-mainPurple text-lg'>{session.user.name}</span>
            <span className='text-mainPurple text-lg'>
              {session.user.email}
            </span>
            <span className='text-mainPurple text-lg'>
              {session.user.address}
            </span>
          </div>
          <div className='flex mx-auto gap-4'>
            <Link href='/profile'>
              <a className='bg-mainPurple p-2.5 px-6 rounded-md text-white font-semibold'>
                Profile
              </a>
            </Link>
            <button
              onClick={handleSignOut}
              className='bg-red-500 p-2.5 px-6 rounded-md text-white font-semibold'
            >
              Logout
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps({ req }) {
  const session = await getSession({ req });
  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }
  return {
    props: { session },
  };
}
